### PR TITLE
Document how to change to a C++ Project

### LINKED ISSUE #117: Document how to switch to a C++ Project
It would be helpful if it were documented what needed to be done to switch to a C++ program.

From what I've read, renaming `main.c` to `main.cpp` is important, but beyond that I'm unsure what additional CMake changes need to be made to get everything (especially the STM32 HAL) to play nicely together.

For example, after making this change I seem to get linker issues building for the STM32F3DISCOVERY:

```
...
CMakeFiles/Project.elf.dir/startup/startup_stm32f303xc.s.obj: In function `LoopFillZerobss':
Project/startup/startup_stm32f303xc.s:111: undefined reference to `main'
```

### PR DESCRIPTION
**Pull request by johnthagen**
Fixes #117

---
This change is [Reviewable](https://reviewable.io/reviews/elmot/clion-embedded-arm/118)

### CODE REVIEW

**Comment by johnthagen** [comment]
@elmot 

> main.c with main() function is auto-generated, and will be rewritten every now and then. The bare bone project should be still based in C, and C++ parts should be called C code

Good point, I was planning to rename back to `main.c` if I needed to regenerate from STM32CubeMX, but we shouldn't prescribe that for the common case. I've removed the comment

> better to add CXX as 3rd or 2nd language rather than add the comment

Done. For pure-C projects, this won't hurt anything either.

> it's not enough to mention C++ here, the compiler should be set up as well.

What do you mean by this? It looks like the template is setting up the correct `c++` compiler. It's been working for me. Anything else need to be done?

**Comment by elmot** [comment]
There should be 
`SET(CMAKE_CXX_COMPILER_WORKS 1)` clause. At least it did not work for me without that.
You may be having multi-target gcc installed, and that's why your g++ works nicely without this line.

PS. Can you, please, reply in reviewable (that purple button at the very top). I use it on daily basis and it seems to be really handy review instrument.

**Comment by johnthagen** [comment]
@elmot I know that exception handling should normally be avoided on embedded tasks, but for completeness I was trying to test if `try`/`catch` would work and the CPU seems to be halting on `throw`. I wanted to be sure our solution here enables as much of C++ as people would want. Any ideas on:

A) If exception unwinding is possible on bare-metal STM32F3/F4, etc.
B) If there are some flags we should document for those wanting to use exception handling within pure C++ code?

**Comment by johnthagen** [comment]
@elmot Sure I'll open a different issue for exception handling.

**Pull request merged**
